networks:
  project-network:
    driver: bridge

volumes:
  pg_data:
  backup_data:

services:
  postgres-kivo:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - backup_data:/tmp/backup
    networks:
      - project-network
    ports:
      - 5432:5432
    mem_limit: 1000M
    cpus: '2.5'

  pgadmin-kivo:
    image: dpage/pgadmin4
    networks:
      - project-network
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: "81"
    ports:
      - "81:81"
    volumes:
      - backup_data:/var/lib/pgadmin/backup
      - ./database/backup:/var/lib/pgadmin/backup
    mem_limit: 1000M
    cpus: '1.5'
    depends_on:
      - postgres-kivo

  backend-app-kivo:
    build:
      args:
         USER: ${USER}
         UID: ${UID:-1000}
      context: ./
      dockerfile: ./docker/php.Dockerfile
    container_name: backend-app-kivo
    networks:
        - project-network
    volumes:
        - ./backend:/var/www
        - ./.docker/docker/php.ini:/usr/local/etc/php/php.ini
        - ./docs:/usr/share/docs
        - ./.docker/docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        - "host.docker.internal:host-gateway"

  frontend-app-kivo:
    build:
      context: ./
      dockerfile: ./docker/nodeJs.DockerFile
      args:
        USER: ${USER}
        UID: ${UID:-1000}
    networks:
      - project-network
    ports:
      - "9000:9000"
      - "4040:4040"
    volumes:
      - ./frontend:/usr/src/app
      - ./docs:/usr/share/docs
    mem_limit: 6500M
    cpus: '5'

  nginx-app:
    image: nginx:alpine 
    volumes:
      - ./backend:/var/www
      - ./.docker/docker/app.conf:/etc/nginx/conf.d/app.conf
    ports:
        - 80:80
        - 82:82
        - 83:83
        - 84:84
        - 85:85
    networks:
      - project-network
